package com.digisafe.guardian.evidence

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import com.google.firebase.database.FirebaseDatabase
import kotlinx.coroutines.tasks.await
import org.json.JSONObject
import java.security.KeyStore
import java.security.Security
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * EvidencePackage: The encrypted, tamper-proof structure stored in Firebase.
 * 
 * ALGORITHM VERSIONS:
 * Version 1: PBKDF2 + AES-256-GCM (Software-based, deprecated)
 * Version 2: Android Keystore + AES-256-GCM (Hardware-backed, current)
 */
data class EvidencePackage(
    val encryptedPayload: String,
    val iv: String,
    val salt: String? = null,
    val hmac: String? = null,
    val algorithmVersion: Int = 2,
    val createdAt: Long = System.currentTimeMillis()
) {
    fun toMap(): Map<String, Any?> = mapOf(
        "encryptedPayload" to encryptedPayload,
        "iv" to iv,
        "algorithmVersion" to algorithmVersion,
        "createdAt" to createdAt
    )
}

/**
 * EvidenceVaultManager: Production-grade forensic evidence management.
 * 
 * SECURITY DESIGN (HARDENED):
 * 1. Root of Trust: Android Keystore System provides hardware-backed key storage.
 * 2. Key Insulation: The AES key is generated inside the TEE/StrongBox and never leaves it.
 * 3. Atomic Authentication: AES-256-GCM provides GCM-Tag (Auth Tag).
 * 4. Integrity Enforcement: Any tampering throws SecurityException immediately.
 */
object EvidenceVaultManager {

    private const val TAG = "EvidenceVaultManager"
    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val AES_MODE = "AES/GCM/NoPadding"
    private const val AUTH_TAG_LENGTH = 128 // Bits
    private const val REQUIRED_IV_LENGTH = 12 // Bytes for GCM

    /**
     * Builds and uploads a hardware-encrypted evidence package.
     * Throws SecurityException if encryption fails.
     */
    suspend fun secureEvidence(
        userId: String,
        eventId: String,
        evidenceData: Map<String, Any>
    ): String {
        try {
            val jsonData = JSONObject(evidenceData).toString()
            val secretKey = getOrCreateSecretKey(userId)

            // 1. Initialize Cipher
            val cipher = Cipher.getInstance(AES_MODE)
            cipher.init(Cipher.ENCRYPT_MODE, secretKey)
            
            // 2. Validate IV Length
            val iv = cipher.iv
            if (iv == null || iv.size != REQUIRED_IV_LENGTH) {
                throw SecurityException("Invalid IV generated by provider")
            }

            // 3. Perform Encryption
            val encryptedBytes = cipher.doFinal(jsonData.toByteArray(Charsets.UTF_8))

            // 4. Assemble Package
            val pkg = EvidencePackage(
                encryptedPayload = Base64.encodeToString(encryptedBytes, Base64.NO_WRAP),
                iv = Base64.encodeToString(iv, Base64.NO_WRAP),
                algorithmVersion = 2
            )

            // 5. Atomic Upload
            FirebaseDatabase.getInstance()
                .getReference("users/$userId/evidence/$eventId")
                .setValue(pkg.toMap()).await()

            Log.d(TAG, "Hardware-guarded evidence vaulted securely")
            return eventId

        } catch (e: Exception) {
            Log.e(TAG, "Encryption operation failed")
            throw SecurityException("Evidence encryption failed", e)
        }
    }

    /**
     * Decrypt and verify an existing evidence package.
     * Throws SecurityException on any cryptographic or integrity failure.
     * Returns null ONLY for legacy (v1) algorithm versions.
     */
    suspend fun decryptEvidence(
        userId: String,
        pkg: EvidencePackage
    ): String? {
        try {
            return when (pkg.algorithmVersion) {
                2 -> decryptV2(userId, pkg)
                1 -> {
                    Log.w(TAG, "Legacy record found: migration required")
                    null
                }
                else -> {
                    throw SecurityException("Unknown algorithm version: ${pkg.algorithmVersion}")
                }
            }
        } catch (e: Exception) {
            if (e is SecurityException) throw e
            
            Log.e(TAG, "Vault access failed")
            throw SecurityException("Evidence decryption failed", e)
        }
    }

    private fun decryptV2(userId: String, pkg: EvidencePackage): String {
        val secretKey = getOrCreateSecretKey(userId)
        val iv = Base64.decode(pkg.iv, Base64.NO_WRAP)
        
        // 1. Explicit IV validation
        if (iv.size != REQUIRED_IV_LENGTH) {
            throw SecurityException("Malformed IV detected")
        }

        val encryptedBytes = Base64.decode(pkg.encryptedPayload, Base64.NO_WRAP)

        val cipher = Cipher.getInstance(AES_MODE)
        val spec = GCMParameterSpec(AUTH_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)
        
        return try {
            val decryptedBytes = cipher.doFinal(encryptedBytes)
            String(decryptedBytes, Charsets.UTF_8)
        } catch (e: AEADBadTagException) {
            // 2. Explicit Integrity Failure Handling
            throw SecurityException("Evidence integrity violation: authentication tag mismatch")
        }
    }

    /**
     * Retrieves or generates a hardware-backed AES key.
     */
    private fun getOrCreateSecretKey(userId: String): SecretKey {
        val keyAlias = "digiSafe_evidence_key_$userId"
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }

        if (keyStore.containsAlias(keyAlias)) {
            return keyStore.getKey(keyAlias, null) as SecretKey
        }

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES, 
            KEYSTORE_PROVIDER
        )

        val spec = KeyGenParameterSpec.Builder(
            keyAlias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setUserAuthenticationRequired(false)
            .setRandomizedEncryptionRequired(true)
            .build()

        keyGenerator.init(spec)
        return keyGenerator.generateKey()
    }
}
